kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: invoke-igwsu
  namespace: customer-details
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  endpoint:
    http:
      target:
        tlsClientProfile: tls-client-profile-default:1.0.0
        url: >-
          'https://sample-api.us-east-b.apiconnect.automation.ibm.com/api' &
          $pathAndQuery()
        urlType: jsonata
        persistentConnections: false
        timeout: 30
        decompressResponse: false
        followRedirects: false
        chunkedUpload: false
