kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: policy-sequence
  namespace: customer-details
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  main:
    - $ref: customer-details:invoke:1.0
  monitoring:
    $ref: customer-details:telemetry:1.0
